ignore:
  - "proptest_regressions"
  - "tests"
  - "CHANGELOG.md"
  - "CODE_OF_CONDUCT.md"
  - "CONTRIBUTING.md"
  - "Cargo.lock"
  - "Cargo.toml"
  - "LICENSE"
  - "README.md"

codecov:
  status:
    project:
      default:
        target: auto
        threshold: 2%
